/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/app-compatibility": {
    /**
     * App compatibility information 
     * @description Returns compatibility information for Flip-managed apps.
     */
    get: operations["get-app-compatibility"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * AppCompatibility 
     * @description Basic compatibility information for flip managed apps
     */
    AppCompatibility: {
      /**
       * @description Presence of this value indicates that some action is required for the app to function properly.
       * Clients should treat the presence of this value as an indicator to stop working with the remote services, even if they do not understand the specific sub properties.
       */
      required_actions?: components["schemas"]["RequiredAppCompatibilityActions"];
      /** @description Links to app stores for updating the app */
      app_stores: (components["schemas"]["AppStoreInfo"])[];
    };
    /**
     * RequiredAppCompatibilityActions 
     * @description Information when actions are required for the app to function properly.
     */
    RequiredAppCompatibilityActions: {
      /** @description If present, an operating system update is required for the application to function properly. */
      os_update?: components["schemas"]["OSUpdateRequiredCompatibilityAction"];
      /** @description If present, an app update is required in order for the app to function properly. */
      app_update?: components["schemas"]["AppUpdateRequiredAppCompatibilityAction"];
      /**
       * @description If present, the app has reached it's end of life and should "uninstall" itself.
       * Presence also implies that the other two values are absent.
       */
      end_of_life?: components["schemas"]["EndOfLifeAppCompatibilityAction"];
    };
    /**
     * EndOfLifeAppCompatibilityAction 
     * @description Information that the client reached end of life and should cease operation.
     */
    EndOfLifeAppCompatibilityAction: {
      message: components["schemas"]["LocalizedLabel"];
    };
    /**
     * OSUpdateRequiredAppCompatibilityAction 
     * @description Information that the operating system has to be updated.
     */
    OSUpdateRequiredCompatibilityAction: {
      /**
       * @description Minimum required operating system version 
       * @example 8.0.1
       */
      min_os_version: string;
      message: components["schemas"]["LocalizedLabel"];
    };
    /**
     * AppUpdateRequiredAppCompatibilityAction 
     * @description Information that the app has to be updated.
     */
    AppUpdateRequiredAppCompatibilityAction: {
      /** @example 4.1.0 */
      min_app_version: string;
      message: components["schemas"]["LocalizedLabel"];
    };
    /**
     * LocalizedLabel 
     * @description Data structure for a dynamic localized label/message/text
     */
    LocalizedLabel: {
      /** @description ISO language code - this might differ from the preferred language when there is no proper translation  available. */
      language: components["schemas"]["LanguageCode"];
      /** @example This is a message */
      text: string;
    };
    /**
     * LanguageCode 
     * @description ISO-639-1 encoded language identifier 
     * @example en-US
     */
    LanguageCode: string;
    /** AppStoreInfo */
    AppStoreInfo: {
      /**
       * @description logical id of the store 
       * @example ios_store
       */
      id: string;
      /**
       * @description human readable app store name 
       * @example Apple Store
       */
      name: string;
      /** Format: uri */
      url: string;
    };
  };
  responses: never;
  parameters: {
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {

  /**
   * App compatibility information 
   * @description Returns compatibility information for Flip-managed apps.
   */
  "get-app-compatibility": {
    parameters: {
      query: {
        /** @description the installed app's type */
        app_type: "DESKTOP" | "MOBILE" | "WEB";
        /** @description the installed app's current version */
        app_version: string;
        /** @description generalized device type */
        device_type: "MOBILE" | "TABLET" | "DESKTOP";
        /** @description operating system identifier */
        os_family: "IOS" | "ANDROID" | "WINDOWS" | "LINUX" | "MACOS" | "OTHER";
        /** @description version of the operating system */
        os_version: string;
        /** @description api level (used for android only) */
        os_api_level?: string;
        /** @description organization identifier in case of a branded app installation */
        organization_id?: string;
      };
      header: {
        /** @description preferred language for localized messages */
        "Accept-Language"?: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["AppCompatibility"];
        };
      };
      /** @description Bad Request */
      400: never;
    };
  };
}
