/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/legallinks": {
    /**
     * Get Organisation Links 
     * @description Retrieve legal and contact links to be displayed
     */
    get: operations["get-links"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * LegalLinks 
     * @description Legal links to be displayed on our frontends before login
     */
    LegalLinks: {
      /**
       * Format: uri 
       * @description Link to website containing the imprint
       */
      imprint: string;
      /**
       * Format: uri 
       * @description Link to website containing our data privacy policy
       */
      privacy: string;
      /**
       * Format: uri 
       * @description Link to website containing the relevant terms and conditions
       */
      terms: string;
      /**
       * Format: uri 
       * @description Link to website containing a contact form
       */
      contact: string;
      /**
       * Format: email 
       * @description General contact email address
       */
      email: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {

  /**
   * Get Organisation Links 
   * @description Retrieve legal and contact links to be displayed
   */
  "get-links": {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["LegalLinks"];
        };
      };
    };
  };
}
