name: "swirl_tokens"
version: "0.0.0"
description: "Swirl Design System Tokens package for Flutter."
homepage: "https://www.getflip.com"
environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.3.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
