import 'package:flutter/widgets.dart';

class FlipLegacyIcons {
  FlipLegacyIcons._();

  static const _kFontFam = 'flip-legacy-icons';
  static const String? _kFontPkg = null;

  static const IconData account_circle = IconData(0xea01, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alternate_email = IconData(0xea02, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData android = IconData(0xea03, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData announcement = IconData(0xea04, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData backup = IconData(0xea05, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beach_access = IconData(0xea06, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark = IconData(0xea07, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud = IconData(0xea08, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coronavirus = IconData(0xea09, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData desktop_windows = IconData(0xea0a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData directions_car_filled = IconData(0xea0b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_calendar = IconData(0xea0c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData email = IconData(0xea0d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emoji_food_beverage = IconData(0xea0e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData event_menu = IconData(0xea0f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook = IconData(0xea10, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favorite = IconData(0xea11, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fitness_center = IconData(0xea12, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flag = IconData(0xea13, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder = IconData(0xea14, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe = IconData(0xea15, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData groups = IconData(0xea16, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help = IconData(0xea17, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image = IconData(0xea18, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_menu = IconData(0xea19, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram = IconData(0xea1a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ios = IconData(0xea1b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData language = IconData(0xea1c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData leaderboard = IconData(0xea1d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lightbulb = IconData(0xea1e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin = IconData(0xea1f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_on = IconData(0xea20, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData loyalty = IconData(0xea21, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData maps_home_work = IconData(0xea22, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notifications = IconData(0xea23, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData open_in_new = IconData(0xea24, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pedal_bike = IconData(0xea25, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pinterest = IconData(0xea26, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData policy = IconData(0xea27, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData push_pin = IconData(0xea28, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData redeem = IconData(0xea29, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData report_problem = IconData(0xea2a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData restaurant = IconData(0xea2b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData roadmap = IconData(0xea2c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData room = IconData(0xea2d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData savings = IconData(0xea2e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings_voice = IconData(0xea2f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_cart = IconData(0xea30, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smartphone = IconData(0xea31, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xea32, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData supervisor_account = IconData(0xea33, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbs_up_down = IconData(0xea34, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter = IconData(0xea35, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wb_sunny = IconData(0xea36, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wechat = IconData(0xea37, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weibo = IconData(0xea38, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData work = IconData(0xea39, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData xing = IconData(0xea3a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData youtube = IconData(0xea3b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
