name: "swirl_icons"
version: "0.0.2"
description: "Swirl Design System Icons package for Flutter."
homepage: "https://www.getflip.com"
environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.3.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
flutter:
  fonts:
    - family: swirl-icons
      fonts:
        - asset: lib/fonts/swirl-icons.ttf
