
//
// styles.dark.dart
//

// Do not edit directly
// Generated on Fri, 24 Feb 2023 07:36:50 GMT



import 'dart:ui';

class SwirlDesignTokensDark {
  SwirlDesignTokensDark._();

    static const actionNeutralDefault = Color(0xFF2A2B2D); /* Used for containers that are low emphasis action elements. */
    static const actionNeutralDisabled = Color(0xFF2A2B2D); /* Used if a component with “Action Neutral/Default” has a disabled state. */
    static const actionNeutralHovered = Color(0xFF323335); /* Used if a component with “Action Neutral/Default” has a hovered state. */
    static const actionNeutralPressed = Color(0xFF3A3B3D); /* Used if a component with “Action Neutral/Default” has a pressed state. */
    static const actionPrimaryDefault = Color(0xFF9191A2); /* Used for containers that are high emphasis action elements. */
    static const actionPrimaryDisabled = Color(0xFF2A2B2D); /* Used if a component with “Action Primary/Default” has a disabled state. */
    static const actionPrimaryHovered = Color(0xFF7B7B8A); /* Used if a component with “Action Primary/Default” has a hovered state. */
    static const actionPrimaryPressed = Color(0xFF666671); /* Used if a component with “Action Primary/Default” has a pressed state. */
    static const backgroundDefault = Color(0xFF191A1C); /* Usually used for the page background and elements that should not elevate from the background. */
    static const backgroundHovered = Color(0xFF232426); /* Used if a component with “Background/Default” has a hovered state. */
    static const backgroundPressed = Color(0xFF2A2B2D); /* Used if a component with “Background/Default” has a pressed state. */
    static const borderCritical = Color(0xFFFB6486); /* Usally used as an border on critical components. */
    static const borderDefault = Color(0x1FFFFFFF); /* Usually used for low emphasis borders and espacially divider elements. */
    static const borderHighlight = Color(0xFF7394D3); /* Used as border color on containers that need to be highlighted (e.g. form fields). */
    static const borderInfo = Color(0xFF73A7F2); /* Usally used as an border on info components. */
    static const borderOnHighlight = Color(0x33BEFFF0); /* Used as border color on containers that have an highlight surface */
    static const borderRadiusBase = 12.00;
    static const borderRadiusFullRound = 99999.00;
    static const borderRadiusL = 16.00;
    static const borderRadiusS = 4.00;
    static const borderRadiusSm = 8.00;
    static const borderRadiusXl = 20.00;
    static const borderRadiusXs = 2.00;
    static const borderStrong = Color(0x33FFFFFF); /* Usually used for high emphasis borders. */
    static const borderSuccess = Color(0xFF68C468); /* Usally used as an border on success components. */
    static const borderWarning = Color(0xFFF9C763); /* Usally used as an border on warning components. */
    static const borderWidth0 = 0.00;
    static const borderWidthDefault = 1.00;
    static const coreCustomerColorDark1Default = Color(0xFF9191A2);
    static const coreCustomerColorDark1Hovered = Color(0xFF7B7B8A);
    static const coreCustomerColorDark1Pressed = Color(0xFF666671);
    static const coreCustomerColorDark2Default = Color(0xFF7394D3);
    static const coreCustomerColorDark2Hovered = Color(0xFF627EB3);
    static const coreCustomerColorDark2Pressed = Color(0xFF506894);
    static const coreCustomerColorDark3Default = Color(0xFF7394D3);
    static const coreCustomerColorDark3Hovered = Color(0xFF627EB3);
    static const coreCustomerColorDark3Pressed = Color(0xFF506894);
    static const coreCustomerColorLight1Default = Color(0xFF15192F);
    static const coreCustomerColorLight1Hovered = Color(0xFF383C4E);
    static const coreCustomerColorLight1Pressed = Color(0xFF5B5E6D);
    static const coreCustomerColorLight2Default = Color(0xFF0026FF);
    static const coreCustomerColorLight2Hovered = Color(0xFF2647FF);
    static const coreCustomerColorLight2Pressed = Color(0xFF4D67FF);
    static const coreCustomerColorLight3Default = Color(0xFF003DAF);
    static const coreCustomerColorLight3Hovered = Color(0xFF265ABB);
    static const coreCustomerColorLight3Pressed = Color(0xFF4D77C7);
    static const coreDecorativeDarkBananaSurface = Color(0xFFECC140);
    static const coreDecorativeDarkBananaSurfaceSubdued = Color(0xFF4D441D);
    static const coreDecorativeDarkBananaText = Color(0xFFECC140);
    static const coreDecorativeDarkBlueberrySurface = Color(0xFFAEC7FF);
    static const coreDecorativeDarkBlueberrySurfaceSubdued = Color(0xFF2A4B74);
    static const coreDecorativeDarkBlueberryText = Color(0xFFAEC7FF);
    static const coreDecorativeDarkChilliSurface = Color(0xFFFF9494);
    static const coreDecorativeDarkChilliSurfaceSubdued = Color(0xFF64353B);
    static const coreDecorativeDarkChilliText = Color(0xFFFF9494);
    static const coreDecorativeDarkGrapeSurface = Color(0xFFD98FF7);
    static const coreDecorativeDarkGrapeSurfaceSubdued = Color(0xFF533071);
    static const coreDecorativeDarkGrapeText = Color(0xFFD98FF7);
    static const coreDecorativeDarkKiwiSurface = Color(0xFF88C897);
    static const coreDecorativeDarkKiwiSurfaceSubdued = Color(0xFF2D482D);
    static const coreDecorativeDarkKiwiText = Color(0xFF88C897);
    static const coreDecorativeDarkPumpkinSurface = Color(0xFFFFAC80);
    static const coreDecorativeDarkPumpkinSurfaceSubdued = Color(0xFF5F4025);
    static const coreDecorativeDarkPumpkinText = Color(0xFFFFAC80);
    static const coreDecorativeDarkRadishSurface = Color(0xFFFE90DF);
    static const coreDecorativeDarkRadishSurfaceSubdued = Color(0xFF5F3051);
    static const coreDecorativeDarkRadishText = Color(0xFFFE90DF);
    static const coreDecorativeLightBananaSurface = Color(0xFFEABA2A);
    static const coreDecorativeLightBananaSurfaceSubdued = Color(0xFFFAF1C8);
    static const coreDecorativeLightBananaText = Color(0xFF9A5C00);
    static const coreDecorativeLightBlueberrySurface = Color(0xFF3F5FA7);
    static const coreDecorativeLightBlueberrySurfaceSubdued = Color(0xFFE6F1FF);
    static const coreDecorativeLightBlueberryText = Color(0xFF3F5FA7);
    static const coreDecorativeLightChilliSurface = Color(0xFFC31C1C);
    static const coreDecorativeLightChilliSurfaceSubdued = Color(0xFFFCE7ED);
    static const coreDecorativeLightChilliText = Color(0xFFC31C1C);
    static const coreDecorativeLightGrapeSurface = Color(0xFF822DA4);
    static const coreDecorativeLightGrapeSurfaceSubdued = Color(0xFFE9DCFF);
    static const coreDecorativeLightGrapeText = Color(0xFF822DA4);
    static const coreDecorativeLightKiwiSurface = Color(0xFF367745);
    static const coreDecorativeLightKiwiSurfaceSubdued = Color(0xFFDCF7DC);
    static const coreDecorativeLightKiwiText = Color(0xFF367745);
    static const coreDecorativeLightPumpkinSurface = Color(0xFFF59031);
    static const coreDecorativeLightPumpkinSurfaceSubdued = Color(0xFFFFE3CA);
    static const coreDecorativeLightPumpkinText = Color(0xFFA74C25);
    static const coreDecorativeLightRadishSurface = Color(0xFFBA1D8E);
    static const coreDecorativeLightRadishSurfaceSubdued = Color(0xFFFFDDF5);
    static const coreDecorativeLightRadishText = Color(0xFFBA1D8E);
    static const coreGray01 = Color(0xFFF2F3F5);
    static const coreGray02 = Color(0xFFE8E9EB);
    static const coreGray03 = Color(0xFFDDDEE0);
    static const coreGray04 = Color(0xFFCCCDD1);
    static const coreGray05 = Color(0xFFA1A2A5);
    static const coreGray06 = Color(0xFF6D6E72);
    static const coreGray07 = Color(0xFF4F5054);
    static const coreGray08 = Color(0xFF3A3B3D);
    static const coreGray09 = Color(0xFF323335);
    static const coreGray10 = Color(0xFF2A2B2D);
    static const coreGray11 = Color(0xFF232426);
    static const coreGray12 = Color(0xFF191A1C);
    static const coreGrayBlack = Color(0xFF000000);
    static const coreGrayWhite = Color(0xFFFFFFFF);
    static const coreOnCustomerColorDark1 = Color(0xFF000000);
    static const coreOnCustomerColorDark2 = Color(0xFF000000);
    static const coreOnCustomerColorLight1 = Color(0xFFFFFFFF);
    static const coreOnCustomerColorLight2 = Color(0xFFFFFFFF);
    static const coreStatusDarkCriticalDefault = Color(0xFFFB6486);
    static const coreStatusDarkCriticalSubdued = Color(0xFF470E1B);
    static const coreStatusDarkInfoDefault = Color(0xFF73A7F2);
    static const coreStatusDarkInfoSubdued = Color(0xFF102648);
    static const coreStatusDarkSuccessDefault = Color(0xFF68C468);
    static const coreStatusDarkSuccessSubdued = Color(0xFF123A12);
    static const coreStatusDarkWarningDefault = Color(0xFFF9C763);
    static const coreStatusDarkWarningSubdued = Color(0xFF392E11);
    static const coreStatusLightCriticalDefault = Color(0xFFD50636);
    static const coreStatusLightCriticalSubdued = Color(0xFFFCE7ED);
    static const coreStatusLightInfoDefault = Color(0xFF145AF5);
    static const coreStatusLightInfoSubdued = Color(0xFFE6F1FF);
    static const coreStatusLightSuccessDefault = Color(0xFF088108);
    static const coreStatusLightSuccessSubdued = Color(0xFFDCF7DC);
    static const coreStatusLightWarningDefault = Color(0xFFF3B703);
    static const coreStatusLightWarningStrong = Color(0xFF935806);
    static const coreStatusLightWarningSubdued = Color(0xFFFAF1C8);
    static const decorationNone = "none";
    static const decorationUnderline = "underline";
    static const decorativeBananaSurface = Color(0xFFECC140); /* Used as a decorative color. */
    static const decorativeBananaSurfaceSubdued = Color(0xFF4D441D); /* Used as a decorative color. */
    static const decorativeBananaText = Color(0xFFECC140); /* Used as a decorative color. */
    static const decorativeBlueberrySurface = Color(0xFFAEC7FF); /* Used as a decorative color. */
    static const decorativeBlueberrySurfaceSubdued = Color(0xFF2A4B74); /* Used as a decorative color. */
    static const decorativeBlueberryText = Color(0xFFAEC7FF); /* Used as a decorative color. */
    static const decorativeChilliSurface = Color(0xFFFF9494); /* Used as a decorative color. */
    static const decorativeChilliSurfaceSubdued = Color(0xFF64353B); /* Used as a decorative color. */
    static const decorativeChilliText = Color(0xFFFF9494); /* Used as a decorative color. */
    static const decorativeGrapeSurface = Color(0xFFD98FF7); /* Used as a decorative color. */
    static const decorativeGrapeSurfaceSubdued = Color(0xFF533071); /* Used as a decorative color. */
    static const decorativeGrapeText = Color(0xFFD98FF7); /* Used as a decorative color. */
    static const decorativeKiwiSurface = Color(0xFF88C897); /* Used as a decorative color. */
    static const decorativeKiwiSurfaceSubdued = Color(0xFF2D482D); /* Used as a decorative color. */
    static const decorativeKiwiText = Color(0xFF88C897); /* Used as a decorative color. */
    static const decorativePumpkinSurface = Color(0xFFFFAC80); /* Used as a decorative color. */
    static const decorativePumpkinSurfaceSubdued = Color(0xFF5F4025); /* Used as a decorative color. */
    static const decorativePumpkinText = Color(0xFFFFAC80); /* Used as a decorative color. */
    static const decorativeRadishSurface = Color(0xFFFE90DF); /* Used as a decorative color. */
    static const decorativeRadishSurfaceSubdued = Color(0xFF5F3051); /* Used as a decorative color. */
    static const decorativeRadishText = Color(0xFFFE90DF); /* Used as a decorative color. */
    static const focusDefault = Color(0xFF7394D3);
    static const fontFamilyCode = "'Fira Mono', Courier, monospace";
    static const fontFamilyText = "'Inter var experimental', 'Inter var', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen-Sans, Ubuntu, Cantarell, 'Helvetica Neue', sans-serif";
    static const fontFamilyTextArabic = "-apple-system, system-ui";
    static const fontFamilyTextChineseSimplified = "'Inter var experimental', 'Inter var', 'Microsoft YaHei New', 微软雅黑, 'Microsoft Yahei', 'Microsoft JhengHei', 宋体, SimSun, sans-serif";
    static const fontFamilyTextChineseTraditional = "'Inter var experimental', 'Inter var', 'Microsoft JhengHei', 微軟正黑體, 'Microsoft JhengHei UI', 'Microsoft YaHei', 微軟雅黑, 宋体, SimSun, sans-serif";
    static const fontFamilyTextJapanese = "'Inter var experimental', 'Inter var', Hiragino Sans, 'ヒラギノ角ゴ ProN W3', 'Hiragino Kaku Gothic ProN', 'メイリオ', Meiryo, Osaka, 'MS PGothic', sans-serif";
    static const fontFamilyTextKorean = "'Inter var experimental', 'Inter var', 'Microsoft JhengHei', 微軟正黑體, 'Microsoft JhengHei UI', 'Microsoft YaHei', 微軟雅黑, 宋体, SimSun, sans-serif";
    static const fontSize2xl = 28.00; /* Usually used as main headline */
    static const fontSizeBase = 16.00; /* Usually used for the body, links and buttons  */
    static const fontSizeLg = 18.00; /* Usually used as level 3 headline */
    static const fontSizeSm = 14.00; /* Usually used for labels and captions */
    static const fontSizeXl = 20.00; /* Usually used as level 2 headline */
    static const fontWeightBold = FontWeight.w700;
    static const fontWeightMedium = FontWeight.w500;
    static const fontWeightNormal = FontWeight.w400;
    static const fontWeightSemibold = FontWeight.w600;
    static const iconCritical = Color(0xFFFB6486); /* Used as critical icon color */
    static const iconDark = Color(0xFF191A1C); /* Used for low contrast decorative colors. */
    static const iconDefault = Color(0xFFA1A2A5); /* Used for low emphasis icons. */
    static const iconDisabled = Color(0xFF4F5054); /* Used if a icon element is disabled. */
    static const iconHighlight = Color(0xFF7394D3); /* Used to highlight icons. */
    static const iconInfo = Color(0xFF73A7F2); /* Used as info icon color */
    static const iconOnActionPrimary = Color(0xFF000000); /* Used as a icon color on containers with action primary color. */
    static const iconOnImage = Color(0xFFFFFFFF); /* Used as a icon color on “Surface On Image/Default”. */
    static const iconOnStatus = Color(0xFF000000); /* Used as a icon color on containers with a status color. */
    static const iconOnSurfaceHighlight = Color(0xFF000000); /* Used as icon color on containers with highlight color. */
    static const iconStrong = Color(0xFFF2F3F5); /* Used for high emphasis icons. */
    static const iconSuccess = Color(0xFF68C468); /* Used as success icon color */
    static const iconWarning = Color(0xFFF9C763); /* Used as warning icon color */
    static const interactiveNeutralDefault = Color(0xFFA1A2A5); /* Used for icon and text that are low emphasis interactive elements. */
    static const interactiveNeutralDisabled = Color(0xFF4F5054); /* Used if a component with “Interactive Neutral/Default” has a disabled state. */
    static const interactiveNeutralHovered = Color(0xFF6D6E72); /* Used if a component with “Interactive Neutral/Default” has a hovered state. */
    static const interactiveNeutralPressed = Color(0xFF6D6E72); /* Used if a component with “Interactive Neutral/Default” has a pressed state. */
    static const interactivePrimaryDefault = Color(0xFF7394D3); /* Used for icon and text that are high emphasis interactive elements. */
    static const interactivePrimaryDisabled = Color(0xFF4F5054); /* Used if a component with “Interactive Primary/Default” has a disabled state. */
    static const interactivePrimaryHovered = Color(0xFF627EB3); /* Used if a component with “Interactive Primary/Default” has a hovered state. */
    static const interactivePrimaryPressed = Color(0xFF506894); /* Used if a component with “Interactive Primary/Default” has a pressed state. */
    static const letterSpacingNormal = 0.00;
    static const letterSpacingTight = -0.22;
    static const letterSpacingTighter = -0.32;
    static const lineHeight2xl = 36.00;
    static const lineHeightBase = 22.00;
    static const lineHeightLg = 24.00;
    static const lineHeightSm = 20.00;
    static const lineHeightXl = 26.00;
    static const onSurfaceHighlightDefault = Color(0xFF627EB3); /* Used to place containers on “Surface Highlight/Default”. */
    static const space0 = 0.00;
    static const space12 = 12.00;
    static const space16 = 16.00;
    static const space2 = 2.00;
    static const space20 = 20.00;
    static const space24 = 24.00;
    static const space32 = 32.00;
    static const space4 = 4.00;
    static const space8 = 8.00;
    static const surfaceCriticalDefault = Color(0xFFFB6486); /* Used as a background for critical surfaces. */
    static const surfaceCriticalSubdued = Color(0xFF470E1B); /* Used for low prio critical background. */
    static const surfaceDefault = Color(0xFF232426); /* Usually used for containers that need to be elevated. */
    static const surfaceHighlightDefault = Color(0xFF7394D3); /* Usually used for containers that need to be highlighted. */
    static const surfaceHighlightHovered = Color(0xFF627EB3); /* Used if a component with “Surface Highlight/Default” has a hovered state. */
    static const surfaceHighlightPressed = Color(0xFF506894); /* Used if a component with “Surface Highlight/Default” has a pressed state. */
    static const surfaceHovered = Color(0xFF2A2B2D); /* Used if a component with “Surface/Default” has a hovered state. */
    static const surfaceInfoDefault = Color(0xFF73A7F2); /* Used as a background for info surfaces. */
    static const surfaceInfoSubdued = Color(0xFF102648); /* Used for low prio info background. */
    static const surfaceNeutralDefault = Color(0xFFCCCDD1); /* Used as a background for neutral surfaces. */
    static const surfaceNeutralSubdued = Color(0xFF2A2B2D); /* Used for low prio neutral background. */
    static const surfaceOnImageDefault = Color(0x66000000); /* Usually used for containers on images */
    static const surfaceOverlayDefault = Color(0xFF2A2B2D); /* Usually used for containers that need to be more elevated. */
    static const surfaceOverlayHovered = Color(0xFF323335); /* Used if a component with “Surface Overlay/Default” has a hovered state. */
    static const surfaceOverlayPressed = Color(0xFF3A3B3D); /* Used if a component with “Surface Overlay/Default” has a pressed state. */
    static const surfacePressed = Color(0xFF323335); /* Used if a component with “Surface/Default” has a pressed state. */
    static const surfaceRaisedDefault = Color(0xFF323335); /* Usually used for elements that need contrast on surfaces or background */
    static const surfaceRaisedHovered = Color(0xFF3A3B3D); /* Used if a component with “On Surface/Default” has a hovered state. */
    static const surfaceRaisedPressed = Color(0xFF4F5054); /* Used if a component with “On Surface/Default” has a pressed state. */
    static const surfaceSuccessDefault = Color(0xFF68C468); /* Used as a background for success surfaces. */
    static const surfaceSuccessSubdued = Color(0xFF123A12); /* Used for low prio success background. */
    static const surfaceWarningDefault = Color(0xFFF9C763); /* Used as a background for warning surfaces. */
    static const surfaceWarningSubdued = Color(0xFF392E11); /* Used for low prio warning background. */
    static const textCritical = Color(0xFFFB6486); /* Used as critical text color */
    static const textDark = Color(0xFF191A1C); /* Used for low contrast decorative colors. */
    static const textDefault = Color(0xFFF2F3F5); /* Used for high emphasis text. */
    static const textDisabled = Color(0xFF4F5054); /* Used if a text element is disabled. */
    static const textHighlight = Color(0xFF7394D3); /* Used to highlight text. */
    static const textInfo = Color(0xFF73A7F2); /* Used as info text color */
    static const textOnActionPrimary = Color(0xFF000000); /* Used as a text color on containers with action primary color. */
    static const textOnImage = Color(0xFFFFFFFF); /* Used as a text color on “Surface On Image/Default”. */
    static const textOnStatus = Color(0xFF000000); /* Used as a text color on containers with a status color. */
    static const textOnSurfaceHighlight = Color(0xFF000000); /* Used as text color on containers with highlight color. */
    static const textSubdued = Color(0xFFA1A2A5); /* Used for low emphasis text. */
    static const textSuccess = Color(0xFF68C468); /* Used as success text color */
    static const textWarning = Color(0xFFF9C763); /* Used as warning text color */
    static const z0 = "0";
    static const z10 = "10";
    static const z20 = "20";
    static const z30 = "30";
    static const z40 = "40";
    static const z50 = "50";
    static const zAuto = "auto";
}