name: Publish

on:
  push:
    branches:
      - APP-12258-design-token-dart-package
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run:
          yarn && yarn prepare-dart-package && cd packages/swirl-tokens && yarn
          build

      - name: "Publish to pub.dev"
        uses: k-paxian/dart-package-publisher@master
        with:
          relativePath: packages/swirl-tokens/dart
          dryRunOnly: true
          skipTests: true
          force: true
          flutter: true
          accessToken: ${{ secrets.PUB_DEV_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.PUB_DEV_REFRESH_TOKEN }}
